addons:
  postgresql: "9.6"
  # postgresql: "10"

  # apt:
    # packages:
    # - postgresql-10
    # - postgresql-client-10

services:
  - postgresql

env:
  global:
    - PGPORT=5432

language: go

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - skir export ue

before_script:
  - PATH="$HOME/gopath/bin:$PATH"

script:
  - go test ./... -v -covermode=count -coverprofile=cover.out
  - goveralls -coverprofile cover.out -service=travis-ci -repotoken $TOKEN