language: go

services:
  - postgresql

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - PATH="$HOME/gopath/bin:$PATH"

script:
  - go test ./... -v -covermode=count -coverprofile=cover.out
  - goveralls -coverprofile cover.out -service=travis-ci -repotoken $TOKEN