addons:
  postgresql: "9.6"
  # postgresql: "10"

  # apt:
    # packages:
    # - postgresql-10
    # - postgresql-client-10

services:
  - postgresql

env:
  global:
    - PGPORT=5432
    - PATH=$PATH:GOPATH/bin
    - GOCMD=go

language: go

install:
  - $GOCMD get -u ./...
  - $GOCMD get golang.org/x/tools/cmd/cover
  - $GOCMD get github.com/mattn/goveralls

script:
  - $GOCMD test -v -covermode=count -coverprofile=cover.out ./...
  - goveralls -coverprofile cover.out -service=travis-ci -repotoken $TOKEN