addons:
  postgresql: "9.6"
  # postgresql: "10"

  # apt:
    # packages:
    # - postgresql-10
    # - postgresql-client-10

services:
  - postgresql

env:
  global:
    - PGPORT=5432

language: go

install:
  - go get -u golang.org/x/vgo
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - PATH="$PATH:GOPATH/bin"

script:
  - vgo build -v  ./...
  - vgo install ./skir/...
  - vgo test -v -covermode=count -coverprofile=cover.out ./...
  - goveralls -coverprofile cover.out -service=travis-ci -repotoken $TOKEN