// Copyright 2011 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// DO NOT EDIT THIS FILE. GENERATED BY mkalldocs.sh.
// Edit the documentation in other files and rerun mkalldocs.sh to generate this one.

// Skir is a tool for developing the Skirmish card game.
//
// Usage:
//
// 	skir command [arguments]
//
// The commands are:
//
// 	card        show information about a specific card
// 	dump        save the current database to disk
// 	export      compile cards from the database to a specific format
// 	ps          fill out Photoshop templates
// 	recover     reload the database from disk
// 	sql         query the database
// 	version     print skir version
//
// Use "skir help [command]" for more information about a command.
//
//
// Show information about a specific card
//
// Usage:
//
// 	skir card [-fmt=[format]] [card name]
//
// Card prints data for the given card to standard output.
//
// The -fmt flag can be used to alter the output format. The valid formats are: "string", "ue", and "xml".
//
//
// Save the current database to disk
//
// Usage:
//
// 	skir dump
//
// Dump saves the current state of the database to the "skirmish_db.sql"
// file in the dreamkeepers-dat repository.
//
//
// Compile cards from the database to a specific format
//
// Usage:
//
// 	skir export [format]
//
// 'Skir export' pulls information for all cards from the database and compiles them into the given format.
//
// The valid formats are:
// 	csv	csv formatted files to use as datasets in Photoshop.
// 		One file is generated for Deck Cards, and another is generated for Non-Deck Cards.
// 	ue	a collection of JSON files for importing into Unreal Engine.
// 		Deck cards are grouped by deck, Non-Deck Cards are grouped together.
//
//
// Fill out Photoshop templates
//
// Usage:
//
// 	skir ps [card name]
//
// 'skir ps' fills out a Photoshop template file with information from the database
//
//
// Reload the database from disk
//
// Usage:
//
// 	skir recover
//
// Recover runs the skirmish_db.sql file from the dreamkeepers-dat repository
// on the database, effectively resetting it to the most recently saved state. To overwrite this
// file, see 'skir dump'.
//
//
// Query the database
//
// Usage:
//
// 	skir sql [PSQL query]
//
// 'Skir sql' queries the database for any desired information.
//
//
// Print skir version
//
// Usage:
//
// 	skir version
//
// Version prints the skir version.
//
//
package main
