// Copyright 2011 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// DO NOT EDIT THIS FILE. GENERATED BY mkalldocs.sh.
// Edit the documentation in other files and rerun mkalldocs.sh to generate this one.

// Skir is a toolset for developing the Skirmish card game.
//
// Usage:
//
// 	skir command [arguments]
//
// The commands are:
//
// 	build       compile cards from database to csv
// 	card        return the text of a given card
// 	qry         query the database
//
// Use "skir help [command]" for more information about a command.
//
//
// Compile cards from database to csv
//
// Usage:
//
// 	skir build
//
// 'Skir build' pulls cards from a database and compiles them into a csv
// file to be used as a dataset in Photoshop.
//
//
// Return the text of a given card
//
// Usage:
//
// 	skir card [card name]
//
//
//
//
// Query the database
//
// Usage:
//
// 	skir qry [PSQL query]
//
// 'Skir qry' queries the database for any desired information.
//
//
package main
