// Copyright 2011 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// DO NOT EDIT THIS FILE. GENERATED BY mkalldocs.sh.
// Edit the documentation in other files and rerun mkalldocs.sh to generate this one.

// Skir is a tool for developing the Skirmish card game.
//
// Usage:
//
// 	skir command [arguments]
//
// The commands are:
//
// 	export      compile cards from the database to a specific format
// 	card        show information about a specific card
// 	sql         query the database
//
// Use "skir help [command]" for more information about a command.
//
//
// Compile cards from the database to a specific format
//
// Usage:
//
// 	skir export [format]
//
// 'Skir export' pulls information for all cards from the database and compiles them into the given format.
//
// The valid formats are:
// 	csv	csv formatted files to use as datasets in Photoshop.
// 		One file is generated for Deck Cards, and another is generated for Non-Deck Cards.
// 	ue	a collection of JSON files for importing into Unreal Engine.
// 		Deck cards are grouped by deck, Non-Deck Cards are grouped together.
//
//
// Show information about a specific card
//
// Usage:
//
// 	skir card [-fmt] [card name]
//
// Card prints data for the given card to standard output.
//
// The -fmt flag can be used to alter the output format. The valid formats are: "string", "ue", and "xml".
//
//
// Query the database
//
// Usage:
//
// 	skir sql [PSQL query]
//
// 'Skir sql' queries the database for any desired information.
//
//
package main
